[functions]
  directory = "api/dist/functions"
  included_files = ["api/dist/**/*.js"]

[[plugins]]
package = "netlify-plugin-inline-functions-env-typescript"

[[plugins]]
package = "netlify-plugin-inngest"

[plugins.inputs]
    path = "/.netlify/functions/inngest"
